project:
  type: website
  #output-dir: docs

website:
  title: "Le carnet des choses diverses"
  # navbar:
    # left:
    #   - href: index.qmd
    #     text: Home
    #   - surleWeb.qml
    #   - about.qmd
  sidebar:
    search: true
    contents:
    - index.qmd
    - about.qmd
    - section: "Projets"
      contents:
        - "projets/this.qmd"
        - "projets/wfc.qmd"
    - section: "sur le Web"
      contents: 
      - surleWeb/listing.qmd
    - Coder.qmd
    - DataViz.qmd
    - Outils.qmd
    - BlogsActu.qmd
    - webapps.qmd
 
format:
  html:
    theme: darkly
    # css: styles.css
    toc: true



